alias tw='/opt/tastyworks/bin/tastyworks'
alias inflate='ruby -r zlib -e "STDOUT.write Zlib::Inflate.inflate(STDIN.read)"'
alias R='R -q --no-save'
alias gnash='gnash-raymii'
alias d8='~/dev/v8/v8/out/x64.release/d8'
alias python='python3'
alias vim='nvim'
alias submit='python3 ~/dev/launch/kattis/submit.py'
alias git-dotfiles='/usr/bin/git --git-dir=/home/lederle/.dotfiles/ --work-tree=/home/lederle'
alias gdf='git-dotfiles'
